version: '3.7'
services:

    postgres:
      image: postgres:15.5
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=postgres
          - PGDATA=/var/lib/postgresql/data/pgdata
          - APP=postgres 
      ports:
        - "5432:5432"
      volumes:
        #- ./postgres/data:/var/lib/postgresql/data
        - ./postgres/init.d:/docker-entrypoint-initdb.d
      container_name: postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: "20s"
        timeout: "20s"
        retries: 3
      networks:
        starter:
          aliases:
            - postgres


networks:
  starter: {}

